### ISSUE TITLE
Types are missing JSDocs

### ISSUE THREAD

**Issue by scottc** [mtennoe/swagger-typescript-codegen#90]
Actual:
Response types are missing JSDocs

```
export type User {
    id: number;
    username: string;
}
```

Expected:
JSDocs containing the definition descriptions.

https://swagger.io/docs/specification/2-0/describing-responses/
```
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        description: The user ID.
      username:
        type: string
        description: The user name.
```

```
/** */
export type User {
    /** {integer} The user ID. */
    id: number;
    /** The user name. */
    username: string;
}
```
